### ISSUE TITLE
Problem with compacting drawers

### ISSUE THREAD

**Issue by cloakable** [jaquadro/StorageDrawers#108]
I'm currently getting Thermal Foundation iron nuggets from an AgriCraft plant farm, but when inserting them into a Compacting drawer they just fill it up without actually compacting into ingots/blocks.

Inserting regular iron ingots into the drawer results in iron blocks, ingots, and tinkers construct nuggets, so there may be an oredict problem somewhere.

**Comment by jaquadro** [comment]
It depends on your mod collection, mod pack, and state of the ore dictionary.  Certain ore dictionary registrations will cause a key to be shut down, because it's indistinguishable from something like "ingotAnyMetal", which would allow all kinds of illegal conversions.  I know this is the case in AgSkies 2.

There's an internal blacklist and whitelist accessible through MineTweaker, which would allow pack authors to fix this on a case-by-case basis.

**Comment by cloakable** [comment]
Aha. How does one go about accessing the black/whitelist using MineTweaker? (I'm making a wild guess here and thinking I want to whitelist TF nuggets?)

**Comment by jaquadro** [comment]
You would add a line like this to a minetweaker script file:
mods.storagedrawers.OreDictionaryWhitelist("nuggetIron");

There is also a blacklist by the same convention.  Some people might want to blacklist gold nuggets, because Thaumcraft registers its gold coins as a nugget.

**Comment by cloakable** [comment]
Okay, I added minetweaker and it seems the Thermal Foundation iron nuggets are listed as both ore:nuggetIron and ore:cropFerrarium, could that be the source of the problem?

Going to try whitelisting nuggetIron.

**Comment by cloakable** [comment]
No such method. Compatibility is good and all, but documentation is really, absurdly needed here.

**Comment by cloakable** [comment]
Okay, figured it. For anyone looking into in the future, the line is:
mods.storagedrawers.OreDictionaryWhitelist.add("nuggetIron");
