### ISSUE TITLE
Duping with Steve's Factory Manager

### ISSUE THREAD

**Issue by Gorgok** [jaquadro/StorageDrawers#116]
You can setup a steve's factory manager system to pull items from a double drawer, craft a block of it, and return it to the other drawer to dupe both material and result of crafting only 1 to start in the other drawer. This can also be done with connected drawers, on a network, but not two separate drawers/networks. 

It also works for other crafting recipes, with only 1 of each material item.

![2015-07-01_18 26 31](https://cloud.githubusercontent.com/assets/2350492/8467152/3e5c8608-2020-11e5-8c3f-ced9c241e8d3.png)
![2015-07-01_18 26 52](https://cloud.githubusercontent.com/assets/2350492/8467153/4586cbf0-2020-11e5-8915-dfe554977cfb.png)
![2015-07-01_18 26 57](https://cloud.githubusercontent.com/assets/2350492/8467155/4bd7fb8c-2020-11e5-9153-9b21b1be741e.png)

**Comment by jaquadro** [comment]
This is going to take some time to unwind.  A few hours of debugging SFM's code and I only have a vague idea of what could be happening.

It's duping when the drawer is initialized with just 1 output item and no input items, which sounds pretty similar to an earlier dupe bug I had with Steve's Workshop.  Since JABBA isn't exhibiting the duping, it's probably something in my inventory balancing code.  Let's hope it is.  SFM hasn't been maintained in a year.

**Comment by jaquadro** [comment]
Fixed in 1.5.10.

**Comment by ukdyl94** [comment]
We're having this same issues with Storage Drawers: StorageDrawers-1.10.2-3.7.9.
