### ISSUE TITLE
Create funnel isn´t been but inside 

### ISSUE THREAD

**Issue by Shadowbee27** [jaquadro/StorageDrawers#1164]
Create funnel isn´t been but inside instead it´s been place on the Draw.
minecraft 1.20.1
storageDrawers: 12.9.7
create: 0.5.1i

**Comment by Jack-McKalling** [comment]
What do you mean is the issue? I don't understand what you're saying.

**Comment by Shadowbee27** [comment]
The create funnel can't be deposited in the draw

**Comment by Jack-McKalling** [comment]
Ah, I see. yes that's something that Create does, not us. The funnel is designed to suppress block interactions if the block is an inventory (paraphrased), so in this case it suppresses being stored inside the drawer. However you can still get it inside by hopper/duct/cable etc from other mods. I don't think there's anything we can do, because that's just how the funnel is made.
