### ISSUE TITLE
Detached Drawer Multiplication Version 1.20.1

### ISSUE THREAD

**Issue by Silverbolt666** [jaquadro/StorageDrawers#1176]
**Forge Version:**  47.3.11
**Minecraft version:** 1.20.1
**Mod Version:** Storage Drawers 1.20.1-12.9.10

### Issue:

When detaching a drawer from the storage that is not upgraded, breaking the storage without the drawers, and placing again, the storage respawns drawers.

The storage drawer also loses the ability to show quantified items if this was previously set.

The issue happens on a clean installation

Another issue that was not possible to replicate in a clean installation was the inability to put filled drawers on upgrades storage containers, this happened on a custom Modpack setting.

### What's expected: 

For the Storage to not spawn new drawers and to keep the previously set definitions.

### Log from clean installation
[latest.log](https://github.com/user-attachments/files/17661126/latest.log)

**Comment by jaquadro** [comment]
This should be fixed in the latest version.

As for the "another issue", that sounds like the "forceDetachedDrawersMaxCapacityCheck" config option is enabled.  That option will prevent a removed drawer from being placed into a "bigger" one in terms of upgrade capacity.  So you can check if that option is enabled -- it's disabled by default.

**Comment by Silverbolt666** [comment]
Thanks for the help!
