### ISSUE TITLE
Possible fix for flickering in optifine

### ISSUE THREAD

**Issue by StefanTT** [jaquadro/StorageDrawers#131]
With optifine the images of the stored items are flickering when the player moves.
This is the same with JABBA and some other blocks, and is primarily no storage drawers bug.

However, I think this could be fixed rather easily. IMO its because two surfaces are on the same position: the front of the storage drawer and the item image. If you move the item image a little bit to before the drawer's front then the flickering should be gone.

I have done OpenGL game programming with Java in the past, but I have not yet done Minecraft modding. So please forgive me if I am wrong with my idea.

**Comment by jaquadro** [comment]
This is how I did the labels originally.  Since flickering still happened for some players even with what I would consider a generous gap, I switched to using polygon offset.

I made a very recent tweak to the polygon offset for block items that seemed to help one person, who otherwise experienced flickering with both render methods.

You can compare version 1.5.9 and 1.5.14 to see the two methods in action.

**Comment by StefanTT** [comment]
Sorry I should have tested the new version before writing.
It's much better in 1.5.14 than in 1.5.6 which I used when writing.

Also setting the optifine option "fast render" to OFF (found in the performance settings) elliminates the last rest of flickering.

Thanks for your help and for this nice mod :+1:
