### ISSUE TITLE
Compacting drawers and Blaze rods

### ISSUE THREAD

**Issue by p455w0rd** [jaquadro/StorageDrawers#142]
So, Botania adds the Blaze Lamps. When I insert a blaze rod into a compacting drawer, it displays the Lamp in the top slot and the rods in the lower left slot, but not blaze powder. Is this intended? Since in vanilla, blaze rods can be shapelessly crafted into powder, I figured this would be implemented. I haven't tried it without Botania, so it could be a bug with that I guess. Just wondering. Pending the answer to this, I am going to go through the code and see what I can do to implement this.

**Comment by jaquadro** [comment]
I'm going to assume Botania blaze lamps can be crafted back into 4 or 9 blaze rods, which is why the compacting drawer would pick it up.  Blaze powder does not craft back into blaze rods.

You can add your own compacting drawer tiers through the MineTweaker API (https://github.com/jaquadro/StorageDrawers/blob/master/src/com/jaquadro/minecraft/storagedrawers/integration/minetweaker/Compaction.java).

**Comment by p455w0rd** [comment]
Awesome..just wondering tho..if i added 2 blaze powder=1 blaze rod to minetweaker, would storage drawers automatically pick that recipe up?

**Comment by jaquadro** [comment]
Yes, it would.
