### ISSUE TITLE
[1.6.2] Rendering weirdness when Mariculture fluid tank is in drawer

### ISSUE THREAD

**Issue by thephoenixlodge** [jaquadro/StorageDrawers#152]
Seems to result in being able to see all water and fluid tanks (including the one in the drawer if looking from other side of the drawer) xray style through the world. Is specific to the tank in the drawer containing a fluid - doesn't occur if the tank is empty.
http://i.imgur.com/U0KwgfF.png
http://i.imgur.com/ZomlOWG.png

**Comment by jaquadro** [comment]
You'll notice that the tank doesn't try to render water when you're holding it or on the ground.  I don't think that's a coincidence.

The ItemRenderer for the tank calls GL11.glClear(GL11.GL_ACCUM) when rendering a liquid.  I don't know why that's needed for inventory rendering, but it's clear it does bad things when the same rendering code is invoked in world render.

The same problem occurs with JABBA barrels, since we both ask Forge to run item render hooks if they are available.  Can you ask Joshie about this and see if there's anything he can do on his end?

I can create a render hook blacklist for this if I need to, but it's a meh solution.

**Comment by jaquadro** [comment]
I've opted to just hardcode the exception for Mariculture tanks.  The change is in 1.7.10.  If it comes up again with another item, then I will look into something more configurable.
