### ISSUE TITLE
Drawers don't accept upgrades

### ISSUE THREAD

**Issue by kwpugh** [jaquadro/StorageDrawers#189]
Running on Minecraft v1.8.9 and Forge 11.15.0.1684.

Right clicking with an upgrade (iron, gold, diamond, etc.) has no affect.

Using: StorageDrawers-1.8.8-2.2.0.jar

**Comment by jaquadro** [comment]
Are you certain the upgrade is not actually applied?  They apply fine for me.

The 1.8 version of the mod will not show an upgrade border, but the upgrade should appear in the UI (shift+right-click with empty hand), and any indicators should reflect the size increase.

While the upgrade border is mainly missing because the rendering system is annoying to work with, lately I'm inclined to make that a permanent design change.

**Comment by kwpugh** [comment]
I will try and let you know.

**Comment by kwpugh** [comment]
Not using 1.8.9 any more, moved on to 1.10.2
