### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by NathanHoffmann** [jaquadro/StorageDrawers#202]
Basically if you put a drawer with items in it into any of the drawbridges from tinkers construct, you can duplicate the items within the drawer every time the drawbridge is cycled. The items drop to the ground as the drawer is pulled into the drawbridge, but the drawer doesn't update and still contains the items.
To get the drawer into the drawbridge's inventory, packing tape was used to pick it up.

Versions:
Minecraft: 1.7.10
Storage Drawers: 1.7.5
Tinker's Construct: 1.8.8

This was in the modpack ftb Infinity, 2.3.5

**Comment by jaquadro** [comment]
This is really a critical problem with TMechworks.

Because it re-deploys the same block you placed into it, regardless of how you modify the deployed block, it behaves badly with a lot of things.  In quick testing, for example:

- I can dupe items with TE caches, since TE caches hold their items on dropping.  Deploy the cache, remove all the items, suck it back in, re-deploy, and there's duped items.
- I can dupe infinite RF with TE energy cells for the same reason.  Deploy a full cell, suck it dry,  it back in and deploy it again.

If TMechworks supports a blacklist, I suggest you start blacklisting anything that "stores" its contents in itemblock form.  A quick fix on the storage drawers side is to disable the packing tape item.  You probably have dollies anyway, so no big deal.

**Comment by NathanHoffmann** [comment]
Guess I should have done more testing and looking into the configs. There is a blacklist set up for TMechworks (Infinity has strongboxes and cache in it) so it seems to be somewhat a known issue. The idea was to have a hidden door of drawers but will be something else instead. :D
