### ISSUE TITLE
Framed drawers overwritten by trim...

### ISSUE THREAD

**Issue by ShadowDrakken** [jaquadro/StorageDrawers#260]
Was trying to place an Oak Trim next to a Framed Drawer, and instead of the trim being placed properly, the Framed Drawer was converted into an Oak Drawer, the actual block ID changed.

Makes trim pretty useless if I can't put it next to drawers in order to create contiguous structures for the controller.

**Comment by jaquadro** [comment]
This only happens if you shift+click the trim directly onto one of the drawer faces.  

I wouldn't call that much of a bug.  However, I will disable this behavior for now, because it might set the expectation that retrimming should work in the other direction as well.  I've got a general idea for how and when that might be supported, at which time I'll re-enable this behavior.

**Comment by Shahelion** [comment]
Will this be fixed for 1.7.10?
