### ISSUE TITLE
Issues with overlay textures for custom draws

### ISSUE THREAD

**Issue by Nazenn** [jaquadro/StorageDrawers#347]
I've noticed a few issues when it comes to rendering the overlays for draws while working on a resource pack. As you can see in the picture below, when the overlay for the face and trim get applied to the draw after using the framing table, they actually render reversed:
https://www.dropbox.com/s/91ju54avt02sg5p/Screenshot%202016-10-05%2016.45.44.png?dl=0
The left and right side are on the wrong side, as the overlay texture I applied to show you here was a set of colors in smaller squares.
I also noticed that despite there being a 'boldtrim' for each of the draw types, it doesn't appear to render or be used anywhere, which leaves the custom draws looking remarkably different and less dark then the normal wood ones:
https://www.dropbox.com/s/7aqkihfm2p5c44e/Screenshot%202016-10-05%2016.51.45.png?dl=0
Not sure if its a bug, but I'd suspect that it may be due to the difference in appearance without it. 

Not part of my report but, I was also curious on why these overlays weren't just merged into a single overlay file that would be applied per draw type, rather then an amalgamation of three separate textures per draw type??

**Comment by jaquadro** [comment]
1) Thanks for the report.  Due to the type of symmetry in those textures I missed that it was being reversed.

2) I'll need to look into the boldtrim issue.  What game version are you on?  Maybe it's something that got missed during the port.  Memory is getting fuzzy but I think the boldtrim is only supposed to be used when you don't provide an alternate trim material.

3) It might be worth revisiting, but a separated version of shading_trim and shading_boldtrim needs to exist to render on the 5 non-front faces of the block (as noted above we're supposed to pick one depending on what you build the drawer with).  It's also rendered over the non-recessed trim portion of the front face, but it's cut up to render on those individual quads.  shading_face and handle are both rendered on the same pass into the recessed portion of the front face, so they could benefit from merging.

So if we merged as much as possible, we'd need these variations: shading_trim, shading_boldtrim, shading_face (trim, face, handle), and shading_boldface (boldtrim, face, handle).  I guess you end up with the same number of textures.

**Comment by jaquadro** [comment]
After taking another look at your second screenshot, something else seems wrong.  The outer edges are a dark wood but the interior cross is not.  How was the drawer built?

**Comment by Nazenn** [comment]
I was playing on 1.10.2 with the latest Storage Drawers version when I took both the screenshots.

The drawer in that second screenshot was made by by inputting a single Oak Trim into a framed drawer using the table provided by the mod, nothing else so I didn't add any special trim or front panel or anything, just an oak trim, and at the time was using only the default Storage Drawers texture. I did it that way, with the normal oak draws behind, to show that the bold trim texture wasn't rendering, as what I can see from extracting the textures from the jar is that the texture for boldtrim for the 4 draw blocks is what controls the darker shading in between the draws which as you can see, isn't present. That same bug happens with all Framed Drawers as far as I can tell.

Fair enough about how merging doesn't really change anything, the explanation is appreciated, I was just curious on how that worked as far as rendering.

**Comment by jaquadro** [comment]
Okay now it makes sense.  Yeah, it should be selecting boldtrim because you only supplied a main material, and no separate trim material.  As a consequence in this case, it would also darken the edges even more.  When you pick a different trim material, then there's natural contrast so you don't need the extra shading.

**Comment by Nazenn** [comment]
Bold trim also controls the coloring in between the draws from what I can tell from the texture though, so from what you're saying, if you pick a trim material, the bold trim gets disabled but then wouldn't that also stop the shading in between the drawers as well? That was actually the main thing that looked off to me is that the cross wasn't applying properly in the 4 framed draws compared to the 'normal' oak ones.

Thanks so much for the explanations though, its a huge help and I know it makes you take time from your project to do so, but it is really appreciated.

**Comment by jaquadro** [comment]
The trim material actually gets rendered between the drawers, that's why the bold trim doesn't need to be used there.  For all of the non-framed drawers, the textures are created from a light base and dark trim.  Shading is only added on top for a subtle effect.

![drawertool](https://cloud.githubusercontent.com/assets/852988/19211303/3d6299fe-8d07-11e6-9c8e-68c98d3f511d.png)

This is a screenshot of the tool I use to create those texture sets (it's in /tools in this repo).  Incidentally I just noticed I only shade the front face so I suppose that lends a stronger argument to merged overlays.

**Comment by Nazenn** [comment]
Thats a handy little tool indeed.
Now I see where the confusion is coming in, which it may be just an unnoticed mistake in the texture for the overlays when porting between versions or something because these are the files extracted from the jar: https://www.dropbox.com/s/k4wad77rw4zuiwf/Screenshot%202016-10-08%2019.00.38.png Most of the shading between drawers is on the boldtrim overlay, rather then trim overlay by itself.

**Comment by jaquadro** [comment]
Both issues should be fixed in 3.3.0.  Happy texturing.

**Comment by Nazenn** [comment]
Thanks a lot for fixing that :) Definitely excited to start work on these again.
