### ISSUE TITLE
StorageDrawers Rotate to North when Pam's Harvestcraft active

### ISSUE THREAD

**Issue by Nitrama** [jaquadro/StorageDrawers#432]
My englich is very bad.

Minecraft:1.11.2
Forge:forge-1.11.2-13.20.0.2232
StorageDrawers:4.1.0
Pams's Harvestcraft:1.11.2c

https://youtu.be/sOiYOiCN2m4

I do not know how to help.
Debug logs?

**Comment by schroffl** [comment]
I'm running the same version of all of these except for Forge, which is at `13.20.0.2236` and I don't have any problems at all. And since the latest version of Forge listed as recommended is `13.20.0.2228` I'd either try to up- or downgrade that. Maybe it helps.

**Comment by Nitrama** [comment]
I have just tried both versions. Is still there the same.

**Comment by jaquadro** [comment]
Please post your logs.

Can you also tell me what happens to items stored in drawers when you load the world and they're all rotated.  Does everything appear to be gone?

**Comment by Nitrama** [comment]
All the items are still there. I'm just trying to re-produce it in a "new world".

**Comment by Nitrama** [comment]
I found the Bug

https://youtu.be/UDUHCfTCp0A

Lastet Log:
http://pastebin.com/7JHfLRWw

**Comment by jaquadro** [comment]
Good that you were able to isolate it.

Pam's block is throwing an exception during loading of TileEntity data on the client.  I wonder if it's limited just to blocks in the same chunk?  Any drawers processed before the press would probably be fine, and then any drawers that should have been processed after the press were skipped because of the error, and so they take a default state.

If you haven't already, please open a bug on Pam's project and attach that log.
