### ISSUE TITLE
Storage controller and Refined storage

### ISSUE THREAD

**Issue by chris4127** [jaquadro/StorageDrawers#478]
major fps drop when refined storage is connected. seem to be when refined stoarage is try to extract stuff
![2017-05-17_16 11 46](https://cloud.githubusercontent.com/assets/28767655/26180147/925d4da0-3b1c-11e7-9536-2c058829949d.png)
![2017-05-17_16 11 38](https://cloud.githubusercontent.com/assets/28767655/26180151/9b3a733a-3b1c-11e7-8e69-c3fc91f1b8df.png)
![2017-05-17_16 11 33](https://cloud.githubusercontent.com/assets/28767655/26180154/9f52000a-3b1c-11e7-8e21-4c939d4ef429.png)

**Comment by jaquadro** [comment]
Could you try loading the sampler mod (http://files.player.to/sampler-1.69.jar), then run "/csampler renderupdates" to see if either a component of RF or Storage Drawers is causing rapid block updates?  That's the only thing I can think of offhand that would introduce low FPS.  Otherwise check to see if there's a tick issue.
