### ISSUE TITLE
[1.12] Drawer recipes not working

### ISSUE THREAD

**Issue by Aenye** [jaquadro/StorageDrawers#515]
Issue with Chameleon 1.12-4.01 (and 1.12-4.02) ans Storage Drawers 1.12-5.1.0 (and 1.12-5.1.2), when using forge 1.12-14.21.0.2359+. Tested only with these two mods as well as with JEI.

Drawers exist correctly as items (when placed in creative and are visible in JEI), but their crafting recipes (1x1, 1x2 and 2x2 drawers) are not available (neither workbench nor JEI). Upgrade recipes work correctly and no issues with the drawers as items in the inventory. No crashes / error reports seen.

**Comment by Placid-Storm** [comment]
Just dropping in to check on the progress, I'm anxious to update my modpack and I'm waiting on this one. I can verify that this issue is happening. I tried making the 1x1 myself using a crafting table. The recipe doesn't work. Gonna look at the code and see what's up.

Haha, taking back everything I just said. I think it an issue with "chestWood" It doesn't look like that name is registered.

**Comment by jaquadro** [comment]
Maybe the way to programatically register recipes with ore dictionary has changed a bit.  Will have to look into it this evening.

**Comment by Placid-Storm** [comment]
Man, you're awesome Jaquadro. I have been trying to tinker with make a json for all 15 drawers. I don't know how to get it to read metadata to automatically add the NBT tag. One of he Forge Tuts I was looking at said that Iregistry should work if you can't use the json though. They were saying that the furnace is still through Iregistry and not json.

**Comment by jaquadro** [comment]
Fixed in 5.1.3.  It ended up being really dumb.  Forgetting the @SubscribeEvent annotation over the function that registers those recipes.
