### ISSUE TITLE
[1.12] Post-fix for the RS/SD error throwing, can't pull from RS storage

### ISSUE THREAD

**Issue by Aalwein** [jaquadro/StorageDrawers#536]
So the error I reported is fixed now (well, it's not throwing errors anymore) but now when the Storage Drawers are connected to the RS storage system via external storage, I cannot pull anything that is stored on the RS storage disks. The items in the drawers interact just fine, but the stuff stored in the RS simply won't "pick up" with a mouse click. Likewise, trying to load a recipe does not load items on the RS disk. Breaking the connection allows the RS storage to work again, but of course the drawers are no longer accessible. No errors are thrown to report.

**Comment by jaquadro** [comment]
@raoulvdberge I might need some insight on this.  Testing with just a standard drawer block, as far as I can tell StorageItemItemRepository.extract() is returning ItemStack.EMPTY when drawers get a request for an item that doesn't exist.  I assume that should be correct, so I don't know why this would prevent other nodes from picking up the request.

Stepping through RS code, this could maybe have something to do with getting back ItemStack.EMPTY from StorageItemItemRepository instead of null, because the ultimate result out of TileController.extract ends up being a full stack of air.

**Comment by Aalwein** [comment]
I can certainly do whatever testing I can for you. Is there anything I can do specifically to help troubleshoot it? I've basically just got a single 16k RS disc for storage and a handful of drawers, maybe 20 of em mixed lot of 2x2s and compactors. With the rs pipes connected, the rs pulls drawer items fine but refuses to work with the items on the disk. Cut the cable and the rs disk works.

**Comment by raoulvdberge** [comment]
Fixing it as we speak

**Comment by raoulvdberge** [comment]
Fixed by https://github.com/raoulvdberge/refinedstorage/commit/99b6c412c9b2360fe078ae113430f2ddfa6b4745

Will be in RS release 1.5.9, coming out in a few minutes

**Comment by jaquadro** [comment]
Thanks!
