### ISSUE TITLE
Compacting Drawers and Mekanism

### ISSUE THREAD

**Issue by brisingraerowing** [jaquadro/StorageDrawers#538]
This is the same issue as #349, but in 1.11.2.

Compacting drawers do not register ingots if a block is used to populate the drawer. It seems either the prior issue was not actually fixed, or a regression happened.

MC: 1.11.2
Forge: 13.20.1.2393
SD: 4.2.10

**Comment by tomelfring** [comment]
Currently also debugging this, but from the side of Mekanism (https://github.com/aidancbrady/Mekanism/issues/4558).

Testing proved the following results:
Inserting one of the ingots registered by Mekanism (Refined Obsidian, Osmium, Bronze, Refined Glowstone, Steel, Copper, Tin) works flawless. The corresponding blocks are being detected.
~~Inserting one of the blocks has some mixed results.
Osmium, Refined Obsidian, Refined Glowstone and steel do not seem to work, the other three are working correctly.~~
Inserting one of the blocks doesn't result in the possibility to extract ingots.

Versions used:
Mekanism: Mekanism-1.11.2-9.3.3.311-fix
StorageDrawers: StorageDrawers-1.11.2-4.2.10
Forge: 13.20.0.2304

~~Debug logging:
[storagedrawers_issue4558.txt](https://github.com/jaquadro/StorageDrawers/files/1169953/storagedrawers_issue4558.txt)~~

If you need any information, feel free to ask. If we found something, we'll let it know here.

--Edit--
Changed some stuff as the ones who where working where from another mod.
Looks like it doesn't like the custom IRecipe which Mekanism is using since a looong time.

**Comment by PearlCanopus** [comment]
Reproduced.

MC: 1.11.2
StorageDrawers 4.2.10
Forge: 13.20.1.2386
Mekanism: 9.3.2.307

Placing an Osmium ingot into a Compacting Drawer works well. It creates Blocks automatically.
Placing an Osmium block into a Compacting Drawer shows up only the block but no ingot.

**Comment by tomelfring** [comment]
Dug somewhere in the code, it's not a StorageDrawer issue.

There's an "issue" (more like feature request) over at Mekanisms repository at https://github.com/aidancbrady/Mekanism/issues/4558
Follow that for up to date info about an implementation. I start working on it right away.

This one can be closed ;)
