### ISSUE TITLE
[1.10.2] Tinker's Contruct ignore privacy of Storage Drawers

### ISSUE THREAD

**Issue by Draskh** [jaquadro/StorageDrawers#560]
If a drawer is locked with the personal key it is possbile to break them with a tool of TC. I don't if this a bug of storage drawers or TC ignores some permissions.

**Comment by jaquadro** [comment]
You can break them with any tool.  It always relied on other world protection mods to do the actual protection part.  The key was added because those mods could stop players from breaking the blocks, but not with interacting with them.

I don't have any plans to change this behavior, since it would give players an easy way to create a kind of "personal bedrock" with griefing implications.

**Comment by Draskh** [comment]
I understand that, but I could be added as a config option so that the server admin can decide about the behavior.
