### ISSUE TITLE
[1.12] Can't extract items from drawer with creative vending upgrade

### ISSUE THREAD

**Issue by boop5** [jaquadro/StorageDrawers#583]
Expectation: I want to transfer unlimited items from my drawer to any inventory.   
Reality: No items get transferred at all.

Example Setup. 
![setup](https://i.imgur.com/OzvdtU1.png)
![servo](https://i.imgur.com/itfyEL3.png)

Playing on ATM3 4.2  with StorageDrawers-1.12.1-5.3.3
Tried Thermal Expansion Itemducts and Extra Utilities 2 Transfer Node

**Comment by jaquadro** [comment]
What version of the mod are you on?

**Comment by boop5** [comment]
Woopsie. Forgot to add this to my original post

Playing on 5.3.3

**Comment by Superfraggle** [comment]
I have experienced the same issue. Same pack - except my setup was several drawers with creative vending upgrade in, I then connected Refined storage to the controller, it could see the inventory, but refused to pull out. AE2 had exactly the same issue.

**Comment by Nicklorion** [comment]
I've got the exact same problem  in "All the mods 3"
- StorageDrawers-1.12.1-5.3.3
- StorageDrawersExtras-1.12-3.1.0

Only way I was able to extract from the drawer is with the creative vending upgrade is using IC2 with the pull upgrade. 
tried several different mods to extract from the drawer without any luck.

**Comment by snaiperskaya** [comment]
I'm seeing the same issue, but even other players cannot access the items. It seems like any method of extraction that is not manually by the original player seems to fail. (I was using a drawer with a vending upgrade to offer some starter items to new players).

**Comment by ShadowDrakken** [comment]
Same issue here in the Horizons 3 modpack

**Comment by NikoLahti** [comment]
aaaand same issue in forever stranded lost souls, version 5.3.4

**Comment by ashbob16478** [comment]
Also an issue in Modern Skyblock 3 Pack Version: 3.4.1.4 Mod Version: 1.12.2-5.3.6

**Comment by cjmcdonald42** [comment]
Has there been any new insight here?
The creative vending upgrade works when I manually remove items but Refined Storage and Thermal Dynamics methods cannot extract items.

I'm trying to create a map for my students in which I wish to keep some items stocked without having to manually refill the bins.

**Comment by GreyMario** [comment]
Has this still not been fixed? I see no reason for this issue to even exist. Please prioritize.

**Comment by cjmcdonald42** [comment]
I used the Creative Cache from TeamCOFH's Thermal Series of mods. A creative cache becomes an infinity dispenser and works with Refined Storage and item ducts.

**Comment by jaquadro** [comment]
@GreyMario a valid criticism.  I've been on a modding break with a bunch of other deadlines, so I'm trying to break back into maintenance of the mod now.  I'm sure I looked at this when it was first reported and couldn't reproduce at the time.  We'll see if it's any different now.

**Comment by jaquadro** [comment]
Heh, I looked back at the original file date and realized this was just a few days before I moved.  Anyway, it sucks that I let it go ignored for so long because it seems to have been an easy fix.

I haven't combed through the backlog of other issues yet, but I put up a new version with this fix, 5.3.8.

**Comment by cjmcdonald42** [comment]
Congratulations on your move.

I totally understand what “busy at work” can do to one’s fun time - no worries there.

Thank you for giving that some attention - I love Storage Drawers.

— 

Do you know about a mod called Compact Drawers by Samtrion? It adds 2x1 and half depth compacting drawers - It’s a great extension of your work - I’m going to play a little with it this weekend to confirm compatibility but wanted to bring it to your attention in case you haven’t seen it yet.

**Comment by GreyMario** [comment]
Oof. Timing issue. Shit happens, I suppose.

Thank you for fixing this. Now to convince all of the pack developers that they need to actually keep up with updating packs every once in a while...

**Comment by willurd** [comment]
I'm seeing this issue in Enigmatica 2: Expert, using 5.3.8

**Comment by willurd** [comment]
Upon further inspection, I've reproduced the problem with a minimal setup:

* Place a creative vending upgrade in an **_empty_** compacting drawer
* Put any item in the compacting drawer
* Connect the drawer to a ME Controller with a Storage Bus
* You will be unable to take items out of the drawer via a ME Crafting Terminal (piping items via other methods such as EnderIO Item Conduits works)

I cannot reproduce this issue with regular drawers.

Also one thing to note, if you put a few items in a compacting drawer and then put the creative vending upgrade in, you'll be able to take that exact amount of items out of the drawer via the ME network, and after you've taken out that many items the drawer becomes cleared out and displays no item if the drawer was unlocked.

So here's what it looks like to me:

* The problem appears to be isolated to compacting drawers.
* Taking items out of a compacting drawer through and ME network, even with the creative vending upgrade, removes the actual items from the drawer that were there before installing the vending upgrade.
* Adding items to a compacting drawer after installing a vending upgrade voids the items, so that there is nothing actually in the drawer (this is probably intended).

Would you like me to create a separate ticket?
