### ISSUE TITLE
Compacting Drawer problem

### ISSUE THREAD

**Issue by BakermanLP** [jaquadro/StorageDrawers#59]
Hello,
I have a small issue about the compacting drawers. But I think it is the easiest way to see a picture of my problem:

![compactingdrawerprob](https://cloud.githubusercontent.com/assets/3873443/7115107/2daf412a-e1e5-11e4-808a-b26c0bdcbeb2.jpg)

Iron nuggets out of copper ingots seems like "magic" :) That works for vanilla ingots, but not for mod ingots.

Can you fix that

**Comment by jaquadro** [comment]
I need to know all your mods providing copper and iron nuggets.  Could you also try inserting each of those 3 items into an empty drawer and seeing if it changes the tiers you get?

I'd also check the usage and recipe on the ingot and nugget just to be sure there's nothing unexpected happening there either.

**Comment by jaquadro** [comment]
I noticed that you've got a pretty big pack that includes IC2.  I've seen ore dictionary problems with this drawer before with IC2 implicated, but I couldn't reproduce it locally with the few other ore providers I have.

Could you install this mod (https://github.com/EXTER7/recipedumper) and use it to dump the ore dictionary and provide that to me?  That will probably be key to seeing what's going on and coming up with any kind of a fix.

**Comment by BakermanLP** [comment]
There would be another way using minetweaker, but never mind, wasn't a big problem. Here are the requested files:
http://solder.projectret.de/vsdump-2015-04-14T082538-oredict.log
http://solder.projectret.de/vsdump-2015-04-14T082540-items.log

If you need more informations, logs or dumps just say something.

**Comment by jaquadro** [comment]
Completely forgot that MineTweaker might be capable of providing that (my first place to look was NEI).

Last night I published a new build with MineTweaker support to update the conversion blacklist. (https://github.com/jaquadro/StorageDrawers/releases/tag/sd-1.3.8).  Try adding "ingotAny" and "nuggetAny" as prefixes to the blacklist, and see if it makes any difference.

If not, then I may need a shaped and shapeless recipe log instead.

**Comment by BakermanLP** [comment]
I'll give it a shoot. But that will be tomorrow. I give you some feedback then

**Comment by BakermanLP** [comment]
And here is the screenshot after adding ingotAny and nuggetAny to the blacklist via minetweaker:

![compactingdrawerprob2](https://cloud.githubusercontent.com/assets/3873443/7152974/884580fc-e345-11e4-947e-5414df96ffe7.jpg)

For documentation purpose here is the minetweaker script:
 mods.storagedrawers.OreDictionaryBlacklist.addPrefix("ingotAny");
 mods.storagedrawers.OreDictionaryBlacklist.addPrefix("nuggetAny");

Thank you for the help!

Michael

**Comment by jaquadro** [comment]
Cool.  I'm actually a little surprised it worked (so keep an eye on it).  I always heard GT did crazy things to the ore dictionary table, and now I know why.

**Comment by BakermanLP** [comment]
I know @GregoriusT and most parts oft bis mod makes sense. Sometimes there
are problematic things in corporation with other mods. In most cases he did
it right. But not always ;-)

Justin Aquadro <notifications@github.com> schrieb am Mi., 15. Apr. 2015
14:34:

**Comment by GregoriusT** [comment]
Ahem, I am not the first one to do that. I saw TerrafirmaCraft do it
and thought that "AnyCopper" and "AnyIron" would be a good Idea to add
in order to make Annealed Copper exchangeable with regular Copper in
most of my Recipes. Same for Iron and Wrought Iron (what later
extended to Meteoric Iron, Deep Iron and Shadow Iron, basically
anything that is considered to be some kind of direct Iron).

My Material System parses pretty much everything inside the OreDict
and doesn't accept technical Names, such as that one, as Component of
an Item, so I don't get problems since I don't have such a simple
Parser, but instead I have to check for every single Name to be
properly registered before I can handle it.

Note that "block[Something]" doesn't work at all for most Names. It
works only for Gold, Iron, Lead, Platinum, Copper, Tin, Steel and
Silver, the rest is guesswork thanks to many Mods registering random
junk as "block[Something]" to the OreDict. That is why I added the
"blockIngot[Something]" Prefix (and some others for Dusts, Gems and
Stuff) in order to have Storage Blocks and their Recipes sorted
properly.

I do so many things with the OreDict (and all of them are even within
the terms of its proper usage), that other people with simpler Parsers
get slightly incompatible.

**Comment by jaquadro** [comment]
Thanks for taking the time to explain some of the reason for those entries.  An 88,000 line ore dictionary log is still quite something to behold.

HarvestCraft was the first one to give me trouble with those kinds of broad categorical entries.  I've since written heuristics that are able to weed out most of those without me needing to blacklist them, but I'll need to revisit them again.

**Comment by jaquadro** [comment]
@BakermanLP could you give the 1.3.9 release a spin and see if it works without the explicit blacklist entries?  I overhauled the dictionary heuristics to be a lot more aggressive about identifying categorical entries.  It should be much more GT-friendly now.  

Of course, something careless like an item registered to both ingotIron and ingotWroughtIron, rather than a parent category like ingotAnyIron, would cause both of those keys to be shut down, but better to be more conservative in this case.

**Comment by GregoriusT** [comment]
If someone would do that, then even GT would fuck up things, and in
this particular case it would do the following:
1. Thanks to that double registration using two valid Materials rather
than just one valid Material it would choose one of them and ignore
the other completely.
2. Because it is an Iron Ingot, and I have set the explicit
unification Target to be the vanilla Iron Ingot, any Wrought Iron
registered as "ingotIron" would unificate towards the vanilla Iron
Ingot, resulting in that Wrought Iron Ingot Item being effectively
deleted from the Game (since it almost always gets replaced with an
Iron Ingot)

**Comment by BakermanLP** [comment]
After having some popcorn and reading through this thread, I have tried to remove the minetweaker commands. And ... yes, it works also now.
