### ISSUE TITLE
[1.14.4] Crash on Launch

### ISSUE THREAD

**Issue by WenXin20** [jaquadro/StorageDrawers#737]
Forge v28.0.102
Minecraft v1.14.4
Storage Drawers v6.0.2

I get this crash on game launch. The first time loading the mod worked fine, but after that I got this crash.
[Crash Report](https://gist.github.com/WenXin20/04fc70fa9d149dfcd8c12476608229d3)

**Comment by jaquadro** [comment]
Was scratching my head for a bit but it started crashing when I updated Forge.  Guess I'm still trying to shoot a moving target.

**Comment by jaquadro** [comment]
I don't think this is a Storage Drawers issue actually.  When SD threw that exception for me, it was because the other Forge threads were in the process of shutting down due to an earlier error.

In my case it was the latest build of SilentMechanisms, but try looking earlier in your log to see if any other mod is throwing an error (or post the whole log here).

**Comment by jaquadro** [comment]
I looked through your list again and saw this entry:
`TreeChoppin-1.14.4-1.2.0.jar TreeChoppin {treechoppin@1.2.0 ERROR}`
Check that first

**Comment by WenXin20** [comment]
Ok, I think I know what went wrong. 

I had incorrectly defined a log block for Tree Choppin config file, but instead of showing the normal dirt background that described what went wrong with the config file, this mod crashed instead.

Fixing the config entry for Tree Choppin stopped the crashing with Storage Drawers.

**Comment by WenXin20** [comment]
Shouldn't this mod not crash at all even if another mod errors? 
Or is this something that should instead be reported to Tree Choppin?

**Comment by jaquadro** [comment]
I could put in a check for this particular thing, but overall I think it's unpredictable what will happen because the startup sequence is broken at that point.  IMO Forge should kill off earlier in this case, but I don't really know what it's doing.

Tree Choppin should probably guard their configs better so an invalid entry does not crash them.  There is nothing they can do about other mods crashing after them, if they crash first, though.

**Comment by WenXin20** [comment]
I'll try reporting it to Tree Chopping, but I don't think that mod is crashing. It's just printing out the error on a dirt background of what went wrong, like the one that pops up if a mod is missing a required mod.

**Comment by jaquadro** [comment]
It's doing something to shut down the loading process though, since the problem went away when you fixed the entry.

I added a null check for this in 6.0.3.  It might crash at a later point, or Forge should kill off itself because loading threads were already shut down.

**Comment by WenXin20** [comment]
Ok, thanks for the help! 
The mods ExplorerCraft and Assisted Progression also had a similar crash because of Tree Choppin, referencing this issue might help them too.
