### ISSUE TITLE
Incompatibility with Ultimate Car Mod

### ISSUE THREAD

**Issue by Cheeyev** [jaquadro/StorageDrawers#741]
Hello; I was playing Minecraft with your mod, as well as a handful of others, and upon adding the [Ultimate Car Mod](https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod), the game crashed after it finished loading the mods with the following report: https://pastebin.com/myKuWh6Y

I assume it has something to do with the model of the drawers and how they're rendered, but I could be wrong. I'm also not sure if it's this mod or the Ultimate Car Mod that's causing it, judging by how it says "{car@1.14.4-2.0.16 ERROR}" in it, but if if it's being caused by this mod, I hope this can help you fix a bug.

**Comment by ProsperCraft** [comment]
Please change the title to "[1.14.4] Please update to Forge 28.1.6"

Same crash here- not using Ultimate car mod-
https://gist.github.com/ProsperCraft/6d200de6f31cc2dba12c8fb84bc6319b

**Comment by jaquadro** [comment]
@Cheeyev Ultimate Car mod is crashing earlier in the loading process.  Forge is responding by terminating a bunch of its loading threads, but some of the other loading threads are continuing to process.  Other mods end up crashing because the game is in an undefined state.

@ProsperCraft In your case, RandomPatches is crashing earlier in the build process.
