### ISSUE TITLE
[Request] Thaumcraft Golem Support

### ISSUE THREAD

**Issue by TehNut** [jaquadro/StorageDrawers#77]
From my testing, it seems that TC Golems cannot interact with Storage Drawers inventories at all. It would be nice if they could do so.

If I missed this support somewhere, I apologize.

**Comment by codewarrior0** [comment]
Golems can work with drawers, but there's a gotcha.

You can't click on the front of the drawer with the bell. You need to do it on any other side. Same for the drawer controller.

**Comment by TehNut** [comment]
Huh... Odd. That also solves my issue with the Super Crafting Frame.

**Comment by jaquadro** [comment]
This might have something to do with the front face not being considered valid for inventory input/output.  It made complete sense for pipes, but maybe not so much for those two.  I could lift the restriction.

Not sure about that other bell thing codewarrior mentioned.

**Comment by codewarrior0** [comment]
It might be the general case of trying to put an item with a right-click ability into a drawer. You simply can't put a drawer key or a drawer upgrade into a drawer, and [trying to put a Chisel into a drawer](https://github.com/TheCricket/Chisel-2/issues/312) crashes to the title screen.

**Comment by jaquadro** [comment]
You can, if you sneak.  Otherwise you have two item handlers trying to invoke special behavior on the same click event.

There's two separate sets of interfaces for manipulating drawer inventories.  There's the IDrawer collection of interfaces, which manages full-size slots and deals with the controller and interactive input/output through the front face.  Then there's the standard IInventory collection of interfaces, which the rest of the Minecraft world works with - including I assume SFCs and Golems.  It's there that there's an artificial restriction on the front face.

**Comment by codewarrior0** [comment]
Then we may have a bug here with somebody's right-click handler. This is what happens when right-clicking on a drawer with and without shift.

(Using 1.4.0... haven't updated yet)

Drawer key: Without shift, locks the drawer. With shift, does nothing.
Drawer upgrade: Without shift, applies the upgrade. With shift, nothing.
Golemancer's Bell: Without shift, plays the bell sound and the bell icon appears in the drawer's face. The bell remains in hand.  WAILA reports a bell in the drawer's inventory, but another item may be inserted replacing the "ghost" bell. If the bell is "inserted" into two slots, inserting another item into one slot updates the other to a blank slot. With shift, plays the bell sound and does nothing.
Chisel: Without shift, crashes to the title screen. With shift, opens the Chisel GUI.
Thaumcraft tools (Pickaxe of the Core etc, which have right-click abilities): Without shift, inserts the item. With shift, performs the tool's right-click ability.

**Comment by jaquadro** [comment]
I'm probably wrong about the sneak insert bit then.  Probably confusing it with being able to insert an upgrade after the same upgrade is already applied.  Bell thing is plain weird.

**Comment by codewarrior0** [comment]
Oh, I didn't try inserting an already applied upgrade. Here we go.

When the same upgrade is already applied, right-clicking without shift inserts the upgrade. With shift, nothing.

**Comment by jaquadro** [comment]
Give 1.4.4 a try, tell me if it solves your issues with SFC and Golems.

**Comment by TehNut** [comment]
Yes that seems to have fixed both issues. Thank you very much!
